<?php

namespace ContainerXTFpbWj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQEkocXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KQEkocX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQEkocX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competenciaDeportivaRepository' => ['privates', 'App\\Repository\\CompetenciaDeportivaRepository', 'getCompetenciaDeportivaRepositoryService', true],
        ], [
            'competenciaDeportivaRepository' => 'App\\Repository\\CompetenciaDeportivaRepository',
        ]);
    }
}
