<?php

namespace ContainerXTFpbWj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DLBgDbBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DLBgDbB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DLBgDbB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetenciaDeportivaController::delete' => ['privates', '.service_locator.eFzgP0o', 'get_ServiceLocator_EFzgP0oService', true],
            'App\\Controller\\CompetenciaDeportivaController::edit' => ['privates', '.service_locator.eFzgP0o', 'get_ServiceLocator_EFzgP0oService', true],
            'App\\Controller\\CompetenciaDeportivaController::index' => ['privates', '.service_locator.KQEkocX', 'get_ServiceLocator_KQEkocXService', true],
            'App\\Controller\\CompetenciaDeportivaController::show' => ['privates', '.service_locator.eFzgP0o', 'get_ServiceLocator_EFzgP0oService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CompetenciaDeportivaController:delete' => ['privates', '.service_locator.eFzgP0o', 'get_ServiceLocator_EFzgP0oService', true],
            'App\\Controller\\CompetenciaDeportivaController:edit' => ['privates', '.service_locator.eFzgP0o', 'get_ServiceLocator_EFzgP0oService', true],
            'App\\Controller\\CompetenciaDeportivaController:index' => ['privates', '.service_locator.KQEkocX', 'get_ServiceLocator_KQEkocXService', true],
            'App\\Controller\\CompetenciaDeportivaController:show' => ['privates', '.service_locator.eFzgP0o', 'get_ServiceLocator_EFzgP0oService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CompetenciaDeportivaController::delete' => '?',
            'App\\Controller\\CompetenciaDeportivaController::edit' => '?',
            'App\\Controller\\CompetenciaDeportivaController::index' => '?',
            'App\\Controller\\CompetenciaDeportivaController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetenciaDeportivaController:delete' => '?',
            'App\\Controller\\CompetenciaDeportivaController:edit' => '?',
            'App\\Controller\\CompetenciaDeportivaController:index' => '?',
            'App\\Controller\\CompetenciaDeportivaController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
