<?php

namespace ContainerXTFpbWj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetenciaDeportivaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eFzgP0o.App\Entity\CompetenciaDeportiva' shared service.
     *
     * @return \App\Entity\CompetenciaDeportiva
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.eFzgP0o": it references class "App\\Entity\\CompetenciaDeportiva" but no such service exists.');
    }
}
