<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT3Aut82\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT3Aut82/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT3Aut82.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT3Aut82\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT3Aut82\App_KernelDevDebugContainer([
    'container.build_hash' => 'T3Aut82',
    'container.build_id' => 'fcc478db',
    'container.build_time' => 1607047225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT3Aut82');
