<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvjAAOb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvjAAOb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHvjAAOb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHvjAAOb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHvjAAOb\App_KernelDevDebugContainer([
    'container.build_hash' => 'HvjAAOb',
    'container.build_id' => 'abfd968d',
    'container.build_time' => 1607103994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvjAAOb');
