<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJ46c0n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJ46c0n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJ46c0n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJ46c0n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRJ46c0n\App_KernelDevDebugContainer([
    'container.build_hash' => 'RJ46c0n',
    'container.build_id' => 'a31b248c',
    'container.build_time' => 1603483677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJ46c0n');
